### ISSUE TITLE
Add minimum supported Joplin version to README

### ISSUE THREAD

**Issue by amitkeret** [JackGruber/joplin-plugin-notelistpreview#20]
I was using Joplin installed via Chocolatey (latest version 2.13.15) and couldn't figure out why changing the plugin's settings was not reflected in the display, or why I couldn't use the First line / Last line feature.
This was all fixed after I updated to the latest version (2.14.17 as of writing this).

**Comment by JackGruber** [comment]
The plugin is supported since Joplin `2.13.2`. 
The plugin can be installed with an incorrect version, but will not be executed and you are informed that Joplin needs to be updated
![grafik](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/24863925/97e6c012-1220-4f86-ac8b-09f631dcdc0f)

After each change in the settings, Joplin must be restarted! 
![grafik](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/24863925/58934ba9-cb4b-4d00-b239-8e6127724982)


Tracker for change reload: https://github.com/JackGruber/joplin-plugin-notelistpreview/issues/3

**Comment by amitkeret** [comment]
Thanks for replying.
> After each change in the settings, Joplin must be restarted!

I had reloaded after every change to settings, and still the aforementioned behavior persisted.
I'm not sure why this wasn't working as expected in version `2.13.15`

**Comment by JackGruber** [comment]
Possible you have quit Joplin only via the `Close` button and the Systray option activated
![grafik](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/24863925/94ae788e-e423-4472-a71c-e1f5a1fcc4d7)
the joplin is only minimized to the Systray and not closed.
When the option is activated you ned to close Joplin via `File > Quit`
